### ISSUE TITLE
You can add animations 

### ISSUE THREAD

**Issue by sanju-0** [Sanju-github002/Chrome-Extension#10]
You can add animation when jokes pop up we can add lit bit animation in that or we can also add animation on joke text to make it more attractive and it make more fun to read jokes.

**Comment by harris2310** [comment]
I could work on this one too!

**Comment by sanju-0** [comment]
Okay great, go ahead 😄

**Comment by harris2310** [comment]
Cool cool!!

**Comment by sanju-0** [comment]
Great work 👍🏻
