### ISSUE TITLE
Add templates for issues

### ISSUE THREAD

**Issue by radville** [Sanju-github002/Chrome-Extension#3]
Issue templates are very helpful for a collaboration repo. When users identify a bug or want to add a new feature, you can provide templates so you can collect all the pertinent information you need to fix a bug or add a new feature. 

We recommend creating a “Report Bug” and “Feature Request” issue template. In case it's helpful, there are some instructions for adding templates [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). 😄 

Some suggested prompts/questions you can add to a “Report Bug” template are:

* Briefly describe the bug
* What is the expected behavior?
* Please provide step by step instructions on how to reproduce the bug

Some suggested prompts/questions you can add to a “Feature Request” issue template are:

* Briefly describe your feature request
* What problem is this feature trying to solve?
* How do we know when the feature is complete?

**Comment by sanju-0** [comment]
Ma'am, i am unable to build issue template can you please help me in this

**Comment by radville** [comment]
Sure! There are some directions [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-templates) for a good way to do it. You should be able to add them from the Settings in your repo. Let me know if you get stuck on any of those steps!

**Comment by sanju-0** [comment]
Done Ma'am 👍🏻 have a look please

**Comment by radville** [comment]
Looks good!
