### ISSUE TITLE
Add Topics

### ISSUE THREAD

**Issue by radville** [Sanju-github002/Chrome-Extension#4]
In Community Exchange, GitHub Topics will help the discoverability of your project. You should create topics pertaining to:

* the tech stack you used on the project
* the subject matter of your repo

There is a limit of 20 topics you can add to your repo. There is no need to go overboard with topics. We recommend under 10 topics. You can add topics by following [these](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository) instructions.

**Comment by sanju-0** [comment]
Done Ma'am 💯

**Comment by radville** [comment]
Thanks! I think it would be great to add one about the subject matter, too, like "jokes" or "humor" or something similar.

**Comment by Sanju-github002** [comment]
Done 👍🏻

**Comment by sanju-0** [comment]
Done Ma'am 👍🏻

**Comment by radville** [comment]
✨
