### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by radville** [Sanju-github002/Chrome-Extension#5]
Your README is already looking really good! 🎉  Because a README is often the first item a visitor will see, here are some additional things I recommend adding:

- [x] How users can get started with the project
      * How to setup the project on their computer
      * How to [contribute to your project](https://docs.github.com/en/get-started/quickstart/contributing-to-projects)
- [x] Mention or link to your code of conduct
- [x] Describe who can contribute to the project

You might also be interested in creating a [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file, but we recommend starting simple with the bullet points above, and once you start to see an increase in users interested in contributing, you should consider a `CONTRIBUTING.md` file so you don’t find yourself overwhelmed with questions from other users.

**Comment by sanju-0** [comment]
Done Ma'am 
please review them once and tell me any suggestions 💯

**Comment by radville** [comment]
Looks good! I opened a PR to suggest some small changes 😄
