### ISSUE TITLE
Add a repo description

### ISSUE THREAD

**Issue by radville** [Sanju-github002/Chrome-Extension#6]
Other than GitHub Topics, your description will be the primary way of catching the users eyes. Your repo description should be clear and concise. Ask yourself:

* In one sentence, how do I convey what my repo does?
* What type of users am I interested in attracting to my repo?
* If I was a user, what words or phrases might spark my interest?

**Comment by sanju-0** [comment]
Done Ma'am 👍🏻

**Comment by radville** [comment]
Looks good! I like how you highlight that it's beginner friendly. Do you want to also include that it generates jokes, so people know what the project does?

**Comment by sanju-0** [comment]
Okay Ma'am i will do it

**Comment by radville** [comment]
I like the additions you made! If you want, here are some copy edits you could consider. I'm just being nit-picky 😄 

```
Best way to get started in a web project by making a cool Chrome Extension that generates random jokes. Beginner friendly code so that you can understand things easily.
```

**Comment by sanju-0** [comment]
Done Ma'am 👍🏻

**Comment by sanju-0** [comment]
Thank you so much for helping me out ☺️
