### ISSUE TITLE
Change API 

### ISSUE THREAD

**Issue by sanju-0** [Sanju-github002/Chrome-Extension#8]
I want to change API with another API through which we get more funny jokes for API changing you should change the mainfest.json file. You should have knowledge of APIs for that.

**Comment by harris2310** [comment]
Hello Sanju, I could give this issue a try!

**Comment by sanju-0** [comment]
Yaa sure go ahead ☺️ All the best 👍🏻 just make sure you give all details and follow all rules and regulations

**Comment by harris2310** [comment]
Cool cool, hopefully i'll pull through!

**Comment by harris2310** [comment]
I've found another api endpoint, should I just replace the original or use both of them to display jokes?

**Comment by sanju-0** [comment]
We can use both to display the jokes

**Comment by harris2310** [comment]
I submitted the pull request!!

**Comment by sanju-0** [comment]
Great Thank you so much for contribution in this Project ☺️✨
